name: chat_app_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.3.0
  emoji_picker_flutter: ^4.3.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  intl: ^0.20.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  saver_gallery: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
